---
# tasks file for filebeat
- name: Import GPG key
  rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
- name: Add Elastic repository
  copy:
    dest: /etc/yum.repos.d/elastic.repo
    content: |
      [elastic-8.x]
      name=Elastic repository for 8.x packages
      baseurl=https://artifacts.elastic.co/packages/8.x/yum
      gpgcheck=1
      gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
      enabled=1
      autorefresh=1
      type=rpm-md
- name: Install Filebeat
  yum:
    name: filebeat
    state: latest
- name: Copy Filebeat configuration
  copy:
    src: ~/ansible-project/roles/filebeat/files/filebeat.yml
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: '0644'
- name: Enable and start Filebeat service
  systemd:
    name: filebeat
    enabled: yes
    state: started
