---
# tasks file for k8s_default
- name: ADD CRI-O keys
  apt_key:
    url: "{{ item }}"
  loop:
    - https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:{{ crio_version }}/{{ os }}/Release.key
    - https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ os }}/Release.key

- name: ADD CRI-O repos
  apt_repository:
    repo: "{{ item }}"
  loop:
    - deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ os }}/ /
    - deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{ crio_version }}/{{ os }}/ /

- name: Update and install packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - cri-o
    - cri-o-runc

- name: Start and enable crio
  systemd:
    name: crio
    state: started
    enabled: yes

- name: Disable swap
  command: swapoff -a

- name: Comment out swap partition in /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '^(.*swap.*)$'
    replace: '#\1'

- name: Enable IP Forwarding
  ansible.builtin.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: yes

- name: Load br_netfilter Module
  ansible.builtin.modprobe:
    name: br_netfilter
    state: present

- name: Add sysctl settings
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1

- name: Apply sysctl settings
  command: sysctl --system

- name: Disable ufw
  ufw:
    state: disabled

- name: Install additional packages
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl

- name: Add Kubernetes apt key
  apt_key:
    url: https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key
    keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add Kubernetes repo
  apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /

- name: Install Kubernetes packages and hold version
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    dpkg_options: 'force-confold,force-confdef'
  loop:
    - kubelet
    - kubeadm
    - kubectl
  notify:
    - Restart kubelet
