filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/*.log
output.kafka:
  hosts: [10.0.242.23:9092]
  topic: "ezcom_test"
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000
